name: Atualizar Playlist do Spotify

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Executar script do Spotify
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: python update_playlist.py

      - name: Enviar JSON atualizado para o repositório
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add playlist.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: atualiza playlist.json automaticamente [skip ci]" && git push)
